apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: pubsubsubscription-sample
  namespace: $project_id
spec:
  ackDeadlineSeconds: 15
  messageRetentionDuration: 86400s
  retainAckedMessages: false
  topicRef:
    name: pubsubsubscription-dep
  deadLetterPolicy:
    deadLetterTopicRef:
      name: pubsubsubscription-dep2
